### ISSUE TITLE
how to make snip only expand in some special environment?

### ISSUE THREAD

**Issue by A6669** [gruvw/latex-setup#1]
For example, if I want to some latex snip only expand in itemize environment?
how to write context function,
also, can hypersnip  do some more complicated cases, such as this https://vi.stackexchange.com/questions/26796/can-this-be-done-with-ultisnips

**Comment by gruvw** [comment]
Yes you can create an environment using hypersnips that will detect the itemize latex environment.  

For the second part though I am not sure that 1) it would be possible and 2) that you would want that to happen because when you would like to use another snippet by pressing tab it will add another item instead.  
What I would do instead is to create a snippet that writes `\n\item` or something similar when you type let's say `itm` and press tab.

You could also add the extension latex workshop, which is automatically adding a `\item` when you press enter inside an itemize environment. (take a look at [https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#Itemize-like-environments](https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#Itemize-like-environments))

If you have further questions consider opening a new issue on a more appropriate repository like `James-Yu/LaTeX-Workshop` or `draivin/hsnips`.  
This repository is more about my snippets and how to use them, so issues here are specific to my snippets and configuration (if you find an error or a conflict in my snippets, you have a question about how my snippets work, ...)
